version: '3.5'

services:
 victimeasyxssserver:
        build: ./victimeasyxssserver
        ports: 
        - "127.0.0.1:1185:1185"
        networks:
          xssnetwork:
            ipv4_address: 172.18.0.2
 victimsessionserver:
        build: ./victimsessionserver
        ports: 
         - "127.0.0.1:3000:3000"
        networks:
          xssnetwork:
            ipv4_address: 172.18.0.3
 attackerserver:
        build: ./attackerserver
        ports:
         - "127.0.0.1:80:80"
        networks:
          xssnetwork:
            ipv4_address: 172.18.0.4

networks:
  xssnetwork:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16
