version: '3.5'

services:
 victim_easy_xss_server:
        build: https://github.com/secf00tprint/victim_easy_xss_server.git
        ports: 
        - "127.0.0.1:1185:1185"
        networks:
          xss_network:
            ipv4_address: 172.18.0.2
 victim_session_xss_server:
        build: https://github.com/secf00tprint/victim_session_xss_server.git
        ports: 
         - "127.0.0.1:3000:3000"
        networks:
          xss_network:
            ipv4_address: 172.18.0.3
 attacker_server:
        build: ./attacker_server
        ports:
         - "127.0.0.1:80:80"
        networks:
          xss_network:
            ipv4_address: 172.18.0.4

networks:
  xss_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16
